fix: move constants in the contract files
At first, we created a `constants.py` file to store the constants in 9b03929, but [some tests were failing](https://github.com/valory-xyz/open-autonomy/runs/8189132511?check_suite_focus=true), because the `aea` framework was throwing an unhandled error [here](https://github.com/valory-xyz/open-aea/blob/main/aea/components/utils.py#L48):
```
KeyError: '__path__'
```

Therefore, we moved the constants to the `__init__.py` file of the contracts in 3ea4de6. However, this was now [failing at the e2e tests](https://github.com/valory-xyz/open-autonomy/runs/8190948023?check_suite_focus=true) when the `aea` framework was trying to load the packages [here](https://github.com/valory-xyz/open-aea/blob/main/aea/components/base.py#L315-L382):
```
ImportError: cannot import name 'GAS_ESTIMATE_ADJUSTMENT' from 'packages.valory.contracts' (unknown location)
```

In order to overcome both limitations, we now move the constants into the contract files, which unavoidably creates some duplication.